name: Benchmarking

on:
  push:
    branches:
      # Long living branches
      - main
      - /^[0-9]+\.[0-9]+$/
      # 👇Add your branch here if benchmarking matters to your work
      - improve-and-bench-uuid

jobs:
  benchmarking:
    name: benchmarking
    runs-on: ubuntu-latest
    needs: [package_vm, package_crypto]
    env:
      RUST_BACKTRACE: 1
      working-directory: ./packages/
      devtools-directory: ./devtools/
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.1
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargocache-v2-benchmarking-rust:1.77.1-{{ checksum "Cargo.lock" }}
      - name: Version information
        run: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - name: Run vm benchmarks (Singlepass)
        working-directory: ${{env.working-directory}}/vm
        run: cargo bench --no-default-features --features="iterator" -- --color never --save-baseline singlepass
      - name: Run crypto benchmarks
        working-directory: ${{env.working-directory}}/crypto
        run: cargo bench -- --color never --save-baseline crypto | tee ~/crypto-bench-result
      - name: Linear Regression Sha1
        working-directory: ${{env.devtools-directory}}/sha1-line-reg
        run: cat ~/crypto-bench-result | cargo run

  package_crypto:
    name: package_crypto
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/crypto
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.1
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargocache-v2-package_crypto-rust:1.77.1-${{ hashFiles('Cargo.lock') }}
      - name: Version information
        run: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - name: Build
        working-directory: ${{env.working-directory}}
        run: cargo build --locked
      - name: Run tests
        working-directory: ${{env.working-directory}}
        run: cargo test --locked

  package_vm:
    name: package_vm
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/vm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.1
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargocache-v2-package_vm-rust:1.77.1-${{ hashFiles('Cargo.lock') }}
      - name: Version information
        run: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - name: Build
        working-directory: ${{env.working-directory}}
        run: cargo build --locked
      - name: Build with all features
        working-directory: ${{env.working-directory}}
        run: cargo build --locked --features iterator,staking,stargate
      - name: Test
        working-directory: ${{env.working-directory}}
        run: cargo test --locked
      - name: Test with all features
        working-directory: ${{env.working-directory}}
        run: cargo test --locked --features iterator,staking,stargate
